DROP TABLE IF EXISTS queries;

CREATE TABLE queries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL,
    query_body VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
